-- MySQL Script generated by MySQL Workbench
-- ср, 05-гру-2018 10:08:33 +0200
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Recipe_book
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Recipe_book` ;

-- -----------------------------------------------------
-- Schema Recipe_book
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Recipe_book` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `Recipe_book` ;

-- -----------------------------------------------------
-- Table `Recipe_book`.`Basis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Recipe_book`.`Basis` ;

CREATE TABLE IF NOT EXISTS `Recipe_book`.`Basis` (
  `Basis_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Basis_name` CHAR(50) NOT NULL,
  PRIMARY KEY (`Basis_ID`, `Basis_name`),
  UNIQUE INDEX `Basis_name_UNIQUE` (`Basis_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `Recipe_book`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Recipe_book`.`Category` ;

CREATE TABLE IF NOT EXISTS `Recipe_book`.`Category` (
  `Category_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Category_name` CHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`Category_ID`),
  UNIQUE INDEX `Category_name_UNIQUE` (`Category_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `Recipe_book`.`Unit_measure`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Recipe_book`.`Unit_measure` ;

CREATE TABLE IF NOT EXISTS `Recipe_book`.`Unit_measure` (
  `Unit_measure_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Unit_measure_name` CHAR(50) NOT NULL,
  PRIMARY KEY (`Unit_measure_ID`),
  UNIQUE INDEX `Unit_measure_name_UNIQUE` (`Unit_measure_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `Recipe_book`.`Ingredient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Recipe_book`.`Ingredient` ;

CREATE TABLE IF NOT EXISTS `Recipe_book`.`Ingredient` (
  `Ingredient_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Ingredient_name` CHAR(50) NOT NULL,
  `Ingredient_unit_measure` INT(11) NULL DEFAULT NULL,
  `Ingredient_cost` DOUBLE UNSIGNED NOT NULL,
  PRIMARY KEY (`Ingredient_ID`),
  UNIQUE INDEX `Ingredient_name_UNIQUE` (`Ingredient_name` ASC) VISIBLE,
  INDEX `fk_Unit_measure_Ingredient_idx` (`Ingredient_unit_measure` ASC) VISIBLE,
  CONSTRAINT `fk_unit_measure`
    FOREIGN KEY (`Ingredient_unit_measure`)
    REFERENCES `Recipe_book`.`Unit_measure` (`Unit_measure_ID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 39
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `Recipe_book`.`Cuisine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Recipe_book`.`Cuisine` ;

CREATE TABLE IF NOT EXISTS `Recipe_book`.`Cuisine` (
  `Cuisine_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Cuisine_name` CHAR(60) NULL DEFAULT NULL,
  PRIMARY KEY (`Cuisine_ID`),
  UNIQUE INDEX `Cuisine_name_UNIQUE` (`Cuisine_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `Recipe_book`.`Recipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Recipe_book`.`Recipe` ;

CREATE TABLE IF NOT EXISTS `Recipe_book`.`Recipe` (
  `Recipe_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Rec_Cuisine_ID` INT(11) NOT NULL,
  `Rec_Basis_ID` INT(11) NOT NULL,
  `Description_cooking_method` TEXT NOT NULL,
  `Recipe_name` CHAR(100) NOT NULL,
  `Caloric_content` INT(11) UNSIGNED NULL DEFAULT NULL,
  `Cooking_time` INT(10) UNSIGNED NOT NULL,
  `Servings_number` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`Recipe_ID`),
  INDEX `Rec_Cuisine_ind` (`Rec_Cuisine_ID` ASC) VISIBLE,
  INDEX `Rec_Basis_ind` (`Rec_Basis_ID` ASC) VISIBLE,
  CONSTRAINT `Recipe_ibfk_1`
    FOREIGN KEY (`Rec_Cuisine_ID`)
    REFERENCES `Recipe_book`.`Cuisine` (`Cuisine_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Recipe_ibfk_6`
    FOREIGN KEY (`Rec_Basis_ID`)
    REFERENCES `Recipe_book`.`Basis` (`Basis_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `Recipe_book`.`Composition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Recipe_book`.`Composition` ;

CREATE TABLE IF NOT EXISTS `Recipe_book`.`Composition` (
  `Composition_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Comp_Ingredient_ID` INT(11) NOT NULL,
  `Comp_Recipe_ID` INT(11) NOT NULL,
  `Quantity` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Composition_ID`),
  INDEX `Comp_Ingredient_ind` (`Comp_Ingredient_ID` ASC) VISIBLE,
  INDEX `Comp_Recipe_ind` (`Comp_Recipe_ID` ASC) VISIBLE,
  CONSTRAINT `Composition_ibfk_1`
    FOREIGN KEY (`Comp_Ingredient_ID`)
    REFERENCES `Recipe_book`.`Ingredient` (`Ingredient_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Composition_ibfk_3`
    FOREIGN KEY (`Comp_Recipe_ID`)
    REFERENCES `Recipe_book`.`Recipe` (`Recipe_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Recipe_book`.`Cooking_method`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Recipe_book`.`Cooking_method` ;

CREATE TABLE IF NOT EXISTS `Recipe_book`.`Cooking_method` (
  `Cooking_method_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Cooking_method_name` CHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`Cooking_method_ID`),
  UNIQUE INDEX `Method_name_UNIQUE` (`Cooking_method_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `Recipe_book`.`Event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Recipe_book`.`Event` ;

CREATE TABLE IF NOT EXISTS `Recipe_book`.`Event` (
  `Event_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Event_name` CHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`Event_ID`),
  UNIQUE INDEX `Event_name_UNIQUE` (`Event_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `Recipe_book`.`Recipe_Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Recipe_book`.`Recipe_Category` ;

CREATE TABLE IF NOT EXISTS `Recipe_book`.`Recipe_Category` (
  `id_recipe` INT(11) NOT NULL,
  `id_category` INT(11) NOT NULL,
  PRIMARY KEY (`id_recipe`, `id_category`),
  INDEX `fk_Category_Recipe_Category_idx` (`id_category` ASC) VISIBLE,
  CONSTRAINT `fk_Category_Recipe_Category`
    FOREIGN KEY (`id_category`)
    REFERENCES `Recipe_book`.`Category` (`Category_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Recipe_Recipe_Category`
    FOREIGN KEY (`id_recipe`)
    REFERENCES `Recipe_book`.`Recipe` (`Recipe_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Recipe_book`.`Recipe_Cooking_method`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Recipe_book`.`Recipe_Cooking_method` ;

CREATE TABLE IF NOT EXISTS `Recipe_book`.`Recipe_Cooking_method` (
  `id_recipe` INT(11) NOT NULL,
  `id_cooking_method` INT(11) NOT NULL,
  PRIMARY KEY (`id_recipe`, `id_cooking_method`),
  INDEX `fk_Cooking_method_Recipe_Cooking_method_idx` (`id_cooking_method` ASC) VISIBLE,
  CONSTRAINT `fk_Cooking_method_Recipe_Cooking_method`
    FOREIGN KEY (`id_cooking_method`)
    REFERENCES `Recipe_book`.`Cooking_method` (`Cooking_method_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Recipe_Recipe_Cooking_method`
    FOREIGN KEY (`id_recipe`)
    REFERENCES `Recipe_book`.`Recipe` (`Recipe_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Recipe_book`.`Recipe_Event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Recipe_book`.`Recipe_Event` ;

CREATE TABLE IF NOT EXISTS `Recipe_book`.`Recipe_Event` (
  `id_recipe` INT(11) NOT NULL,
  `id_event` INT(11) NOT NULL,
  PRIMARY KEY (`id_recipe`, `id_event`),
  INDEX `id_event_idx` (`id_event` ASC) VISIBLE,
  CONSTRAINT `id_event`
    FOREIGN KEY (`id_event`)
    REFERENCES `Recipe_book`.`Event` (`Event_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_recipe`
    FOREIGN KEY (`id_recipe`)
    REFERENCES `Recipe_book`.`Recipe` (`Recipe_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
